version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:latest
    steps:
      - run:
         name: Building kernel
            command: |
            bash .circleci/build.sh
workflows:
  version: 2.1
    cooking:
    jobs:
      - compile
