
version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:jammy-20211029
   steps:
      - run:
          command: |
            apt update && apt upgrade -y
            apt install -f -y git
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            git clone --depth=1 https://github.com/missgoin/lavender.git -b main builder_kernel
            cd builder_kernel
            cp -af sources.list /etc/apt/
            cp -af 99own /etc/apt/apt.conf.d/
            apt install -f -y bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
            bash .circleci/lavender.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
